//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WIS.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class WIS_Reports
    {
        public int ID_report { get; set; }
        public string report_name { get; set; }
        public int report_type_ID { get; set; }
        public System.DateTime report_creation_date { get; set; }
        public int report_user_ID { get; set; }
    
        public virtual WIS_Report_Types WIS_Report_Types { get; set; }
        public virtual WIS_Users WIS_Users { get; set; }
    }
}
