//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WIS.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class WIS_Requests
    {
        public int ID_request { get; set; }
        public int request_asset_ID { get; set; }
        public int request_user_ID { get; set; }
        public System.DateTime request_date { get; set; }
        public int request_status_ID { get; set; }
        public Nullable<int> request_approved_by_user_ID { get; set; }
        public Nullable<System.DateTime> request_approval_date { get; set; }
        public string request_note { get; set; }
    
        public virtual WIS_Assets WIS_Assets { get; set; }
        public virtual WIS_Request_Statuses WIS_Request_Statuses { get; set; }
        public virtual WIS_Users WIS_Users { get; set; }
        public virtual WIS_Users WIS_Users1 { get; set; }
    }
}
