//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WIS.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class WIS_Asset_Histories
    {
        public int ID_asset_history { get; set; }
        public int history_asset_ID { get; set; }
        public System.DateTime history_event_date { get; set; }
        public string history_event_type { get; set; }
        public string history_description { get; set; }
        public int history_user_ID { get; set; }
    
        public virtual WIS_Assets WIS_Assets { get; set; }
        public virtual WIS_Users WIS_Users { get; set; }
    }
}
