//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WIS.ApplicationData
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class WIS_Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WIS_Users()
        {
            this.WIS_Asset_Disposals = new HashSet<WIS_Asset_Disposals>();
            this.WIS_Asset_Histories = new HashSet<WIS_Asset_Histories>();
            this.WIS_Assets = new HashSet<WIS_Assets>();
            this.WIS_Reports = new HashSet<WIS_Reports>();
            this.WIS_Requests = new HashSet<WIS_Requests>();
            this.WIS_Requests1 = new HashSet<WIS_Requests>();
        }
    
        public int ID_user { get; set; }
        public string user_firstname { get; set; }
        public string user_lastname { get; set; }
        public string user_login { get; set; }
        public byte[] user_password_hash { get; set; }
        public string user_email { get; set; }
        public int user_role_ID { get; set; }
        public string user_department { get; set; }

        [NotMapped]
        public string RoleName => this.WIS_User_Roles?.user_role_name ?? "Неизвестно"; 
        
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WIS_Asset_Disposals> WIS_Asset_Disposals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WIS_Asset_Histories> WIS_Asset_Histories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WIS_Assets> WIS_Assets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WIS_Reports> WIS_Reports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WIS_Requests> WIS_Requests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WIS_Requests> WIS_Requests1 { get; set; }
        public virtual WIS_User_Roles WIS_User_Roles { get; set; }
    }
}
